# Generated by Django 6.0.2 on 2026-03-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_amount'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead'),
        ),
    ]
