# Generated by Django 6.0.2 on 2026-03-03 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='crm_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CRMTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_teams_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_crm_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='accounts.crmteam'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'guard_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.role')),
            ],
            options={
                'db_table': 'role_has_permissions',
                'unique_together': {('permission', 'role')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='accounts.RoleHasPermission', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.team'),
        ),
        migrations.CreateModel(
            name='CRMTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.crmteam')),
            ],
            options={
                'db_table': 'crm_team_invitations',
                'ordering': ['-created_at'],
                'unique_together': {('crm_team', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CRMTeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.crmteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_team_user',
                'ordering': ['-created_at'],
                'unique_together': {('crm_team', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('team', 'name', 'guard_name')},
        ),
        migrations.CreateModel(
            name='ModelHasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=255)),
                ('model_id', models.BigIntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_roles', to='accounts.role')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_roles', to='accounts.team')),
            ],
            options={
                'db_table': 'model_has_roles',
                'indexes': [models.Index(fields=['model_id', 'model_type'], name='model_has_r_model_i_3c7ad3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=255)),
                ('model_id', models.BigIntegerField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to='accounts.permission')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to='accounts.team')),
            ],
            options={
                'db_table': 'model_has_permissions',
                'indexes': [models.Index(fields=['model_id', 'model_type'], name='model_has_p_model_i_9a9be0_idx')],
            },
        ),
    ]
