# Generated by Django 6.0.2 on 2026-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('team_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_sources_new',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('team_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_statuses_new',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('team_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('person_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('organisation_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('lead_status_id', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('lead_source_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('qualified', models.BooleanField(default=False)),
                ('expected_close', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('user_created_id', models.BigIntegerField(blank=True, null=True)),
                ('user_updated_id', models.BigIntegerField(blank=True, null=True)),
                ('user_deleted_id', models.BigIntegerField(blank=True, null=True)),
                ('user_restored_id', models.BigIntegerField(blank=True, null=True)),
                ('user_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('user_assigned_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leads_new',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team_id'], name='leads_new_team_id_922ebf_idx'), models.Index(fields=['person_id'], name='leads_new_person__42a5b2_idx'), models.Index(fields=['organisation_id'], name='leads_new_organis_923428_idx'), models.Index(fields=['lead_status_id'], name='leads_new_lead_st_7a4686_idx'), models.Index(fields=['lead_source_id'], name='leads_new_lead_so_60b2e5_idx'), models.Index(fields=['user_owner_id'], name='leads_new_user_ow_0df1ef_idx'), models.Index(fields=['user_assigned_id'], name='leads_new_user_as_841caf_idx'), models.Index(fields=['-created_at'], name='leads_new_created_d5f3e6_idx')],
            },
        ),
    ]
